name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        # Version of PostgreSQL to use
        postgresql version: latest
        # POSTGRES_DB - name for the default database that is created
        postgresql db: chirper_test 
        # POSTGRES_USER - create the specified user with superuser power
        postgresql user: pg_user
        # POSTGRES_PASSWORD - superuser password
        postgresql password: pg_password 
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      env:
        DATABASE_POSTGRESQL_USERNAME: pg_user
        DATABASE_POSTGRESQL_PASSWORD: pg_password
      run: mix test
